name: Dry Run Promotion

env:
  SERVICE_ACCOUNT_ID: ${{ vars.SERVICE_ACCOUNT_ID }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  TENANT_BASE_URL: ${{ vars.TENANT_BASE_URL }}
  REALMS: ${{ vars.REALMS }}
  SCRIPT_PREFIXES: ${{ vars.SCRIPT_PREFIXES }}
  SERVICE_ACCOUNT_CLIENT_ID: ${{ vars.SERVICE_ACCOUNT_CLIENT_ID }}
  SERVICE_ACCOUNT_SCOPE: ${{ vars.SERVICE_ACCOUNT_SCOPE }}
  CONFIG_DIR: ${{ github.workspace }}
  TENANT_ENV_UPPER_FQDN: ${{ vars.TENANT_ENV_UPPER_FQDN }}
  SERVICE_ACCOUNT_UPPER_CLIENT_ID: ${{ vars.SERVICE_ACCOUNT_UPPER_CLIENT_ID }}
  SERVICE_ACCOUNT_UPPER_ID: ${{ vars.SERVICE_ACCOUNT_UPPER_ID }}
  SERVICE_ACCOUNT_UPPER_KEY: ${{ secrets.SERVICE_ACCOUNT_UPPER_KEY }}
  SERVICE_ACCOUNT_PROMOTION_SCOPE: ${{ vars.SERVICE_ACCOUNT_PROMOTION_SCOPE }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pspromodev
    strategy:
      matrix:
        node-version: [ 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install external repo
      run: git clone https://github.com/ForgeRock/fr-config-manager.git
    - name: Install config promote
      run: |
          cd fr-config-manager
          npm install --ws
          npm install axios
          apt-get update && sudo apt-get install -y jq
          cd packages/fr-config-promote
          npm link
    - name: Check locked status
      id: check_status
      run: |
        OUTPUT=$(fr-config-promote check-locked-status)
        echo "Raw output:"
        echo "$OUTPUT"
        
        # Save to file (optional for debugging)
        echo "$OUTPUT" > status.json
        
        # Extract whether state is locked
        IS_LOCKED=$(echo "$OUTPUT" | jq -r '.lowerEnv.state == "locked"')
        PROMOTION_ID=$(echo "$OUTPUT" | jq -r '.promotionId')
        
        echo "is_locked=$IS_LOCKED" >> $GITHUB_OUTPUT
        echo "promotion_id=$PROMOTION_ID" >> $GITHUB_OUTPUT
    - name: Run dry run promotion if locked
      if: steps.check_status.outputs.is_locked == 'true'
      run: |
       echo "Environment is locked. Running dry promotion..."
       fr-config-promote run-dryrun-promotion
